/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Microsoft
 */
public class Belanja extends javax.swing.JFrame {

    /**
     * Creates new form Belanja
     */
    public Belanja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HB1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HB2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        HB3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        HB4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Diskon = new javax.swing.JTextField();
        BtnOk1 = new javax.swing.JButton();
        BtnOk2 = new javax.swing.JButton();
        BtnOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pembayaran");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 20, 140, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga Barang 1");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 70, 110, 17);
        getContentPane().add(HB1);
        HB1.setBounds(140, 60, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Barang 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 110, 17);
        getContentPane().add(HB2);
        HB2.setBounds(140, 100, 190, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Harga Barang 3");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 110, 17);
        getContentPane().add(HB3);
        HB3.setBounds(140, 140, 190, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga Barang 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 110, 17);
        getContentPane().add(HB4);
        HB4.setBounds(140, 180, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Diskon");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 230, 70, 17);
        getContentPane().add(Diskon);
        Diskon.setBounds(140, 220, 190, 30);

        BtnOk1.setText("Proses");
        BtnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOk1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOk1);
        BtnOk1.setBounds(50, 270, 90, 23);

        BtnOk2.setText("Reset");
        BtnOk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOk2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOk2);
        BtnOk2.setBounds(150, 270, 90, 23);

        BtnOk.setText("Exit");
        BtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOkActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOk);
        BtnOk.setBounds(250, 270, 90, 23);

        TA.setEditable(false);
        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 310, 230, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\deni ibi\\P. Web Dinamis\\bootstrap4\\crystal maiden.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -10, 410, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOk1ActionPerformed
        int nama = Integer.parseInt(HB1.getText());
        int Absen = Integer.parseInt(HB2.getText());
        int mapel = Integer.parseInt(HB3.getText());
        int Nilai = Integer.parseInt(HB4.getText());
        int diskon = Integer.parseInt(Diskon.getText());
        int total = nama+Absen+mapel+Nilai;
        int bayar = total - total*diskon/100;

        TA.setText("Harga Barang 1 : "+"Rp "+nama+"\n"+"Harga Barang 2 : "+"Rp "+Absen+"\n"+"Harga Barang 3 : "+"Rp "+mapel+"\n"+"Harga Barang 4 : "+"Rp "+Nilai+"\n"+"Total Harga : "+"Rp "+total+"\n"+"Diskon : "+
            diskon+" %"+"\n"+"Total Bayar : "+"Rp "+bayar);
    }//GEN-LAST:event_BtnOk1ActionPerformed

    private void BtnOk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOk2ActionPerformed
        TA.setText("");
        HB1.setText("");
        HB2.setText("");
        HB3.setText("");
        HB4.setText("");
        Diskon.setText("");

    }//GEN-LAST:event_BtnOk2ActionPerformed

    private void BtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOkActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Belanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Belanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Belanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Belanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Belanja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOk;
    private javax.swing.JButton BtnOk1;
    private javax.swing.JButton BtnOk2;
    private javax.swing.JTextField Diskon;
    private javax.swing.JTextField HB1;
    private javax.swing.JTextField HB2;
    private javax.swing.JTextField HB3;
    private javax.swing.JTextField HB4;
    private javax.swing.JTextArea TA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
